### ISSUE TITLE
config-sample.yaml instead of config.yaml

### ISSUE THREAD

**Issue by lingej** [micromata/swd#1]
Hi Chris,

please ship a config-sample.yaml instead of config.yaml so extracting the release zip will not overwrite an existing config file.

Best regards
Joerg

**Comment by chclaus** [comment]
Hej @lingej,

quite nice idea. I've fixed that issue in [f0612c6](https://github.com/micromata/swd/commit/f0612c64227e435ff1deacc045434f2982f8608d).

You'll find that enhancement in Release v0.2.0. 😄 

Best,
Christian
