### ISSUE TITLE
http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by lingej** [micromata/swd#3]
Hi Christian
running swd behind a haproxy sometimes result in an error 

swd[15065]: 2018/04/24 07:38:32 http: multiple response.WriteHeader calls

This happens on permission errors.
swd is running as user www-data and www-data has not permission on .gitignore file

Apr 24 08:02:08 het71 swd[15065]: 2018/04/24 08:02:08 http: multiple response.WriteHeader calls
Apr 24 08:02:08 het71 swd[15065]: time="2018-04-24T08:02:08+02:00" level=error msg="open /www/aaa.bbb.de/.gitignore: permission denied"

Jörg

**Comment by chclaus** [comment]
Hej @lingej,

this issue is potentially fixed with 76c23dc. Could you please give it a try?

Thanks a lot! 😃 

Best,
Christian

**Comment by lingej** [comment]
Hi Christian

this issue is now fixed!

Thanks!

**Comment by chclaus** [comment]
Hej @lingej,

I'm glad to hear that :)
